version: '3.3'

services:
  proxy:
    image: nginx
    ports:
      - "4202:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./client.pem:/etc/nginx/client.pem
      - ./client.key:/etc/nginx/client.key
